# dotnet-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoapp
  template:
    metadata:
      labels:
        app: photoapp
    spec:
      containers:
        - name: photoapp
          image: image-registry.openshift-image-registry.svc:5000/bluebird182-dev/photo-album-app:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-secret
          env:
            - name: ConnectionStrings__DefaultConnection
              value: "Host=postgresql;Port=5432;Database=photoalbum;Username=admin;Password=admin1234"
