# dotnet-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoapp
  template:
    metadata:
      labels:
        app: photoapp
    spec:
      containers:
        - name: photoapp
          image: image-registry.openshift-image-registry.svc:5000/bluebird182-dev/photo-album-app:latest
          ports:
            - containerPort: 80
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: connection-string
              #value: "Host=postgresql.bluebird182-dev.svc.cluster.local;Port=5432;Database=photoalbum;Username=admin;Password=admin1234"
